### ISSUE TITLE
Can't make createRemote works

### ISSUE THREAD

**Issue by Miaourt** [AlexxNB/derver#1]
Hello Alex, thanks for this awesome tool !

When I'm using derver like this, I can't get "createRemote" to work
```JS
let test = derver.createRemote({
  pubdir: "public",
  host: "localhost",
  port: 1312,
  remote: true,
  watch: false,
});
setInterval(() => test.reload(), 3000);
```

The "test.reload()" keep giving me `[Derver remote]: Warning:connect ECONNREFUSED 127.0.0.1:1312`, and indeed the dev server isn't started.

So I tried with :

```JS
derver.derver({
  pubdir: "public",
  host: "localhost",
  port: 1312,
 remote: "licorne",
 watch: false,
});
let test = derver.createRemote("licorne");
console.log(test);
setInterval(() => test.reload(), 3000);
```

And the `console.log(test);` give me the correct 
```
{
  reload: [Function: reload],
  console: [Function: console],
  error: [Function: error]
}
```

But nothing is reloaded with the `setInterval`, I'm up to provide you with any extra info needed if you tell me what you need, hope it's enough tho !

Thanks.

**Comment by AlexxNB** [comment]
Just tested, and looks working with this code: 
![изображение](https://user-images.githubusercontent.com/10389013/111875501-2b12d700-89ab-11eb-941d-f432b028ffc3.png)

**Comment by AlexxNB** [comment]
Be sure you have `[Livereload] Ready` message in console when open your page in browser.

**Comment by Miaourt** [comment]
Thanks, but it doesn't changed much it seems...
After a bit more investigation, it seems that not watching any directory (by setting watch to `false`, for example) disable the livereload feature, leading to my issues !
I'm using something else to watch file (here esbuild's watcher), so I wanted to _not_ monitor my public directory with derver's watcher

**Comment by AlexxNB** [comment]
Yes, currently livereload is working only when any watcher is set. I think it is good idea to enable livereload also when `remote` option is set. Thanks.
> Use `esbuild.watch` carefully, because it uses file polling instead handling OS events. It may cause more CPU usage and less battery live on huge amount of files.

**Comment by AlexxNB** [comment]
It was a bug. It should work in 0.4.14

**Comment by Miaourt** [comment]
Awesome, thanks !
